### ISSUE TITLE
ViewControllerのコードをまとめる

### ISSUE THREAD

**Issue by s11y** [milanista0702/ThirdEverNote#16]
リファクタリングしといたから、コピペせずに真似てください
https://github.com/milanista0702/ThirdEverNote/commit/09bc6f6c532484e71ec972729b3d9653dd6d4327

**Comment by s11y** [comment]
@milanista0702 宿題やってるみたいでNice!!
ただコードは書いてるかい？
`CalendarLayout`とかGitHubに上がってないよ

**Comment by milanista0702** [comment]
@ShinokiRyosei 
project.pbxprojの方見ながら書いたらThirdEverNoteのファイルが開かなくなって
書き直してる次第です

**Comment by s11y** [comment]
project.pbxprojは自分で書いちゃダメ！
やるのはproject.pbxprojをみて、どういうファイルが追加されてるかだけ見て、ドラッグ&ドロップするなり、新しいファイルつくるなり、ファイル消すなりして

**Comment by milanista0702** [comment]
前のコミットしたとこからproject.pbxprojはダウンロードして入れました
多分解決だと思います

**Comment by s11y** [comment]
解決したの確認した！！
Good Job!
それ伝えてなくてごめん
