### ISSUE TITLE
ViewControllerのTableViewCell

### ISSUE THREAD

**Issue by milanista0702** [milanista0702/ThirdEverNote#17]
`todolabel`のところに長文書いた時に
cellの高さを変えるのをできるようにする

あと日付のTextCellのとこのフォントサイズ下げる

**Comment by s11y** [comment]
http://yuu.1000quu.com/use_a_custom_cell_in_swift

**Comment by s11y** [comment]
テーブルビューのカスタムセルの作り方をググって実装
