### ISSUE TITLE
共有できるようにする

### ISSUE THREAD

**Issue by milanista0702** [milanista0702/ThirdEverNote#7]

**Comment by milanista0702** [comment]
Schedule、ToDoesとUserを繋げる中間テーブルを作る

**Comment by milanista0702** [comment]
![img_8632](https://user-images.githubusercontent.com/19407384/31662530-af67d8fe-b379-11e7-8db1-44beed75d5e4.JPG)

- [x] UISwitchのif文
- [x]  アラート出す
- [x]  GroupCreateViewController の下のMemberCellをつくる
- [x]  SearchGroupViewControllerのGroupCellを作る
- [x]  それぞれのokした時の動き

**Comment by milanista0702** [comment]
UISwitchがonになってもalertが出ない

**Comment by s11y** [comment]
`Use of string literal for Objective-C selectors is deprecated; use '#selector' instead`のところ見るとできると思う
http://glassonion.hatenablog.com/entry/2016/06/07/214819

**Comment by milanista0702** [comment]
とりあえずその場にある配列で検索かけるところまでは行った

**Comment by milanista0702** [comment]
MiddleGroup のNiftyCloudに保存する

**Comment by milanista0702** [comment]
Group,MiddleGroup共にNiftyCloudに保存はできたから

- [ ] MenberArray for文回す
- [ ] TodoとScheduleにそれぞれ追加のif文
